import { Book } from "./shared/models/Book";


export const sample_books: Book[] = [
	{
		id:'0330362143',
		name: 'Temple',
		author: 'Matthew Reilly',
		favourite: false,
		stars: 4.5,
		imageUrl: 'assets/covers/matthew-reilly-temple.jpg',
		categories: ['Action', 'Fast Paced', 'Fiction'],
	},
	{
		id:'1743517017',
		name: 'The Great Zoo of China',
		author: 'Matthew Reilly',
		favourite: true,
		stars: 5,
		imageUrl: 'assets/covers/matthew-reilly-the-great-zoo-of-china.jpg',
		categories: ['Dragons', 'Fantasy', 'Fiction'],
	},
	{
		id:'1742612393',
		name: 'The Tournament',
		author: 'Matthew Reilly',
		favourite: false,
		stars: 4,
		imageUrl: 'assets/covers/matthew-reilly-the-tournament.jpg',
		categories: ['Fantasy', 'Puzzles', 'Chess'],
	},
	{
		id:'1409156052',
		name: 'The Lincoln Lawyer',
		author: 'Michael Connelly',
		favourite: false,
		stars: 4,
		imageUrl: 'assets/covers/michael-connelly-the-lincoln-lawyer.jpg',
		categories: ['True Crime', 'Thriller'],
	},
	{
		id:'0425265625',
		name: 'Tower Lord',
		author: 'Anthony Ryan',
		favourite: false,
		stars: 4,
		imageUrl: 'assets/covers/anthony-ryan-tower-lord.jpg',
		categories: ['Fantasy', 'Action','Adventure'],
	},
	{
		id:'0316097446',
		name: 'Zoo',
		author: 'James Patterson',
		favourite: false,
		stars: 4.5,
		imageUrl: 'assets/covers/james-patterson-zoo.jpg',
		categories: ['Fantasy', 'Fiction','Animals'],
	},
	{
		id:'074754624X',
		name: 'Harry Potter and the Goblet of Fire',
		author: 'J. K. Rowling',
		favourite: true,
		stars: 5,
		imageUrl: 'assets/covers/jk-rowling-harry-potter-goblet-of-fire.jpg',
		categories: ['Fantasy', 'Fiction','Magic'],
	},
	{
		id:'9780007466863',
		name: 'A Darkness at Sethanon',
		author: 'Raymond E. Feist',
		favourite: true,
		stars: 5,
		imageUrl: 'assets/covers/raymond-feist-darkness-at-sethanon.jpg',
		categories: ['Fantasy', 'Fiction','Magic'],
	},
]
